version: "3"
services:
  web:
    container_name: nginx2
    ports: 
      - "8081:80"
    image: nginx
    volumes: 
      - "D:/projects/test:/usr/share/nginx/html"
    networks: 
      - net-test
networks: 
  net-test:
      